Revert "Bump spring security related libraries to 5.5.0"
This reverts commit ad2746b78323b249eb6bb7d15eb65b2feb6a449d.

This stopped the pods from starting, with e.g.

video-service-545bdbb9d9-zclxh:video-service
org.springframework.beans.factory.BeanCreationException: Error creating
bean with name 'springSecurityFilterChain' defined in class path
resource
[org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]:
Bean instantiation via factory method failed; nested exception is
org.springframework.beans.BeanInstantiationException: Failed to
instantiate [javax.servlet.Filter]: Factory method
'springSecurityFilterChain' threw exception; nested exception is
java.lang.NullPointerException